task:
  name: SingleStageDetectionTask
  params:
    backbone_name: MMResNet
    backbone_params:
        depth: 50
        num_stages: 4
        out_indices: [0, 1, 2, 3]
        frozen_stages: 1
        norm_cfg:
          type: 'BN'
          requires_grad: false
        norm_eval: true
        style: 'caffe'
        init_cfg:
          type: Pretrained
          checkpoint: https://download.openmmlab.com/pretrain/third_party/resnet50_caffe-788b5fa3.pth
    num_scales: 4
    neck_name: FPN
    neck_params:
      out_channels: 256
      start_level: 1
      add_extra_convs: on_output
      num_outs: 5
      relu_before_extra_convs: true
    head_name: FCOSHead
    head_params:
      num_classes: &num_classes 80
      strides: [8, 16, 32, 64, 128]
      feat_channels: 256
      stacked_convs: 4
      train_cfg:
        assigner:
          type: MaxIoUAssigner
          pos_iou_thr: 0.5
          neg_iou_thr: 0.4
          min_pos_iou: 0
          ignore_iof_thr: -1
      test_cfg:
        nms_pre: 1000
        min_bbox_size: 0
        score_thr: 0.05
        nms:
          type: nms
          iou_threshold: 0.5
        max_per_img: 100
    inputs:
      - shape: [3, &height 800, &width 1344]
        dtype: &input_dtype float32

joint_loss:
  normalize_weights: false
  losses:
    - name: MMFocalLoss
      tag: loss_cls
      weight: 1.0
      params:
        use_sigmoid: True
        gamma: 2.0
        alpha: 0.25
      mapping:
        pred: flatten_cls_scores
        target: flatten_labels
        avg_factor: num_pos
    - name: MMIoULoss
      tag: loss_bbox
      weight: 1.0
      mapping:
        pred: pos_decoded_bbox_preds
        target: pos_decoded_target_preds
        weight: pos_centerness_targets
        avg_factor: centerness_denorm
    - name: MMCrossEntropyLoss
      tag: loss_centerness
      weight: 1.0
      params:
        use_sigmoid: True
      mapping:
        cls_score: pos_centerness
        label: pos_centerness_targets
        avg_factor: num_pos

optimization:
  - optimizer:
      name: SGD
      params:
        lr: &base_lr 0.001
        momentum: 0.9
        weight_decay: 0.0001
      paramwise_cfg:
        bias_lr_mult: 2.0
        bias_decay_mult: 0.0
    scheduler:
      name: MultiStepLR
      params:
        milestones: [23]

data:
  TRAIN:
    - dataloader:
        batch_size: &bs 8
        num_workers: &n_workers 8
        drop_last: false
        shuffle: true
      dataset:
        name: COCODetection
        params:
          train: true
          download: true
          data_folder: &data_folder ${oc.env:HOME}/coco_detection/data
          input_dtype: *input_dtype
          bbox_dtype: *input_dtype
          channel_order: 'bgr'
        augment:
          - name: HorizontalFlip
        transform:
          - &resize
            name: FitResize
            params:
              max_height: *height
              max_width: *width
          - &normalize
            name: Normalize
            params:
              mean: [102.9801, 115.9465, 122.7717]
              std: [1.0, 1.0, 1.0]
              max_pixel_value: 1.0
          - &pad
            name: PadIfNeeded
            params:
              min_height: *height
              min_width: *width
              border_mode: 0
              value: 0
          - &totensor
            name: ToTensorV2
  VALID:
    - dataloader:
        batch_size: *bs
        num_workers: *n_workers
        drop_last: false
        shuffle: false
      dataset:
        name: COCODetection
        params:
          train: false
          download: true
          data_folder: *data_folder
          input_dtype: *input_dtype
          bbox_dtype: *input_dtype
          channel_order: 'bgr'
        transform:
          - *resize
          - *normalize
          - *pad
          - *totensor

trainer:
  accelerator: 'gpu'
  max_epochs: 24
  precision: 32
  num_sanity_val_steps: 2

logger:
  log_dir: '${oc.env:HOME}/coco_detection/logs'
  experiment_name: fcos_mmresnet50_x800_1344
  timestamp: '${now:%Y-%m-%d}/${now:%H-%M-%S}'
  name: TensorBoardLogger

hydra:
  run:
    dir: &logs_dir '${logger.log_dir}/${logger.experiment_name}/${logger.timestamp}'

callbacks:
  - name: ModelCheckpoint
    params:
      dirpath: *logs_dir
      monitor: valid/MMDetMAP_50
      save_top_k: 1
      save_last: true
      mode: max
      save_weights_only: False
  - name: FinalizeLogger
  - name: TQDMProgressBar
    params:
      refresh_rate: 200

metrics:
  - name: MMDetectionMAP
    tag: MMDetMAP_50
    params:
      iou_thr: 0.5
      num_classes: *num_classes
    mapping:
      preds: prediction
      target: target
    phases: [VALID, TEST]
  - name: MMDetectionMAP
    tag: MMDetMAP_75
    params:
      iou_thr: 0.75
      num_classes: *num_classes
    mapping:
      preds: prediction
      target: target
    phases: [ VALID, TEST ]
  - name: CocoEvalMAP
    tag: CEMAP
    params:
      compute_on_step: false
      displayed_metrics: ["map", "map_50", "map_75", "map_small", "map_medium", "map_large"]
    mapping:
      preds: prediction
      target: target
    phases: [VALID, TEST]
