task:
  name: SingleStageDetectionTask
  params:
    backbone_name: tf_efficientnet_b2_ns
    backbone_params:
      pretrained: true
      in_channels: 3
    pooling_name: YOLOV3Neck
    head_name: YOLOV3Head
    head_params:
      in_channels: [512, 256, 128],
      out_channels: [1024, 512, 256],
      num_classes: &num_classes 80
      anchor_generator:
        type: YOLOAnchorGenerator
        base_sizes: [[[116, 90], [156, 198], [373, 326]],
                        [[30, 61], [62, 45], [59, 119]],
                        [[10, 13], [16, 30], [33, 23]]]
        strides: [32, 16, 8]
      bbox_coder:
        type: YOLOBBoxCoder
      featmap_strides: [32, 16, 8]

    inputs:
      - shape: [3, &height 416, &width 416]
        dtype: &input_dtype bfloat16

joint_loss:
  losses:
    - name: MMCrossEntropyLoss
      tag: classification_loss
      weight: 1.0
      params:
        use_sigmoid: True
        reduction: sum
      mapping:
          cls_score: pred_label
          label: target_label
          weight: pos_mask
    - name: MMCrossEntropyLoss
      tag: confidence_loss
      weight: 1.0
      params:
        use_sigmoid: True
        reduction: sum
      mapping:
          cls_score: pred_conf
          label: target_conf
          weight: pos_and_neg_mask
    - name: MMCrossEntropyLoss
      tag: xy_loss
      weight: 2.0
      params:
        use_sigmoid: True
        reduction: sum
      mapping:
          cls_score: pred_xy
          label: target_xy
          weight: pos_mask
    - name: MMMSELoss
      tag: wh_loss
      weight: 2.0
      params:
        use_sigmoid: True
        reduction: sum
      mapping:
          pred: pred_wh
          target: target_wh
          weight: pos_mask

optimization:
  - optimizer:
      name: SGD
      params:
        lr: &base_lr 0.001
        momentum: 0.9
        weight_decay: 0.0005
    scheduler:
      name: OneCycleLR
      params:
        max_lr: *base_lr
#        total_steps: None
        epochs: &num_epochs 273
        steps_per_epoch: 930
        pct_start: 0.1
        anneal_strategy: 'cos'
        cycle_momentum: True
        base_momentum: 0.85
        max_momentum: 0.95
        div_factor: 25.0
        final_div_factor: 10000.0
        three_phase: false
      pl_params:
        interval: step

data:
  TRAIN:
    - dataloader:
        batch_size: 64
        num_workers: 4
        drop_last: true
        shuffle: true
      dataset:
        name: COCODetection
        params:
          train: true
          download: true
          data_folder: &data_folder ${oc.env:HOME}/.cache/torchok/data/coco
          input_dtype: *input_dtype
          bbox_dtype: *input_dtype

        augment:
          - name: HorizontalFlip
          - name: OneOf
            params:
              p: 0.7
              transforms:
                - name: ElasticTransform
                  params:
                    border_mode: 1
                - name: GridDistortion
                - name: GaussNoise
                - name: ColorJitter
                  params:
                    brightness: 0.2
                    contrast: 0.2
                    saturation: 0.2
                    hue: 0.1
          - name: OneOf
            params:
              p: 0.7
              transforms:
                - name: ElasticTransform
                  params:
                    border_mode: 1
                - name: GridDistortion
                - name: GaussNoise
                - name: ColorJitter
                  params:
                    brightness: 0.2
                    contrast: 0.2
                    saturation: 0.2
                    hue: 0.1
        transform:
          - &resize
            name: Resize
            params:
              height: *height
              width: *width
          - &normalize
            name: Normalize
            params:
              mean: [ 0.5, 0.5, 0.5 ]
              std: [ 0.25, 0.25, 0.25 ]
          - &totensor
            name: ToTensorV2
  VALID:
    - dataloader:
        batch_size: 128
        num_workers: 8
        drop_last: false
        shuffle: false
      dataset:
        name: COCODetection
        params:
          train: false
          download: true
          data_folder: *data_folder
          input_dtype: *input_dtype
          bbox_dtype: *input_dtype
        transform:
          - *resize
          - *normalize
          - *totensor

trainer:
  accelerator: 'gpu'
  max_epochs: *num_epochs
#  limit_train_batches: 10
#  limit_val_batches: 10
#  log_every_n_steps: 1000
  precision: bf16
  num_sanity_val_steps: 2

hydra:
  run:
    dir: '${logger.log_dir}/${logger.experiment_name}/${logger.timestamp}'

logger:
  log_dir: '${oc.env:HOME}/.cache/torchok/logs/coco_detection'
  experiment_name: yolov3_efficientnet_b2
  timestamp: '${now:%Y-%m-%d}/${now:%H-%M-%S}'
  name: TensorBoardLogger

checkpoint:
  monitor: valid/F1Score
  save_last: true
  mode: max
  export_to_onnx: true

metrics:
  - name: Accuracy
    mapping:
      preds: prediction
      target: target
  - name: F1Score
    mapping:
      preds: prediction
      target: target
