task:
  name: ClassificationTask
  params:
    backbone_name: resnet18
    backbone_params:
      pretrained: true
      in_channels: 3
    pooling_name: Pooling
    head_name: ClassificationHead
    head_params:
      num_classes: &num_classes 10
    inputs:
      - shape: [3, &height 32, &width 32]
        dtype: &input_dtype float16

joint_loss:
  losses:
    - name: CrossEntropyLoss
      mapping:
          input: prediction
          target: target

optimization:
  - optimizer: 
      name: Adam
      params:
        lr: 0.0001
    scheduler:
      name: ExponentialLR
      params:
        gamma: 0.97

data:
  TRAIN:
    - dataloader:
        batch_size: 128
        num_workers: 8
        drop_last: true
        shuffle: true
      dataset:
        name: CIFAR10
        params:
          input_dtype: *input_dtype
          train: true
          download: true
          data_folder: &data_folder ${oc.env:HOME}/.cache/torchok/data/cifar10
        transform:
          - &resize
            name: Resize
            params:
              height: *height
              width: *width
          - &normalize
            name: Normalize
            params:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - &totensor
            name: ToTensorV2
  VALID:
    - dataloader:
        batch_size: 128
        num_workers: 8
        drop_last: false
        shuffle: false
      dataset:
        name: CIFAR10
        params:
          input_dtype: *input_dtype
          train: false
          download: true
          data_folder: *data_folder
        transform:
          - *resize
          - *normalize
          - *totensor

trainer:
  accelerator: 'gpu'
  max_epochs: 30
  limit_train_batches: 10
  limit_val_batches: 10
  log_every_n_steps: 1000
  precision: 16
  num_sanity_val_steps: 0

hydra:
  run:
    dir: '${logger.log_dir}/${logger.experiment_name}/${logger.timestamp}'

logger:
  log_dir: '${oc.env:HOME}/.cache/torchok/logs/'
  experiment_name: cifar10
  timestamp: '${now:%Y-%m-%d}/${now:%H-%M-%S}'
  name: TensorBoardLogger

checkpoint:
  monitor: valid/F1Score
  save_last: true
  mode: max
  export_to_onnx: true

metrics:
  - name: Accuracy
    mapping: 
      preds: prediction
      target: target
  - name: F1Score
    mapping: 
      preds: prediction
      target: target
