task:
  name: DetectionTask
  params:
    backbone_name: csp_darknet_p5 #darknet53 #csp_darknet_p5 
    backbone_params:
      in_chans: &num_channels 3
      pretrained: false
    input_size: [ *num_channels, &height 640, &width 640]
    neck_name: YOLOXPAFPN
    head_name: YOLOXHead
    head_params:
      num_classes: &num_classes 1
    hat_name: YOLOXHat

loss:
  loss_list:
    - name: BCEWithLogitsLoss
      params:
        target_fields:
          target: cls_targets
          input: cls_pred
    - name: DetectionIoU
      params:
        mode: square
        target_fields:
          target: bbox_target
          input: bbox_pred
          num_total_samples: num_total_samples
    - name: BCEWithLogitsLoss
      params:
        target_fields:
          target: obj_target
          input: obj_pred
    
optimizers:
  name: SGD
  params:
    lr: &initial_lr 0.001
    weight_decay: 0.00005
    momentum: 0.9
    nesterov: true

schedulers:
  name: ExponentialLR
  params:
    gamma: 0.9


data:
  common_params:
    data_folder: "/workdir/rbayazitov/torchok_detector/"
    # input_dtype: float16

  train_params:
    name: DetectionDataset
    dataloader_params: &dataloader_params
      use_custom_collate_fn: true
      batch_size: 4
      num_workers: 12
      shuffle: true
      drop_last: false
    params:
      path_to_datalist: "train.csv"
    transform:
      - &normalize
        name: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      - &resize
        name: Resize
        params:
            height: *height
            width: *width
      - &totensor
        name: ToTensorV2
    augment:
      - name: ColorJitter
        params:
          p: 0.5
      
  valid_params:
    name: DetectionDataset
    dataloader_params: *dataloader_params
    params:
      path_to_datalist: "valid.csv"
    transform:
      - *normalize
      - *totensor
    augment:
      - *resize
    #   - *pad

trainer:
  # gpus: [0]
  max_epochs: 10
  progress_bar_refresh_rate: 1
  check_val_every_n_epoch: 1
  # precision: 16
  # amp_level: 'O2'
  # amp_backend: 'apex'

log_dir: '/workdir/logs/detectors'
experiment_name: yolox

logger:
  logger: tensorboard
  log_graph: false

checkpoint:
  monitor: valid/loss
  save_last: true
  mode: min
  every_n_val_epochs: 10
#  every_n_train_steps: 100

profiler:
  name: 'simple'
  save_profile: false

metrics:
  - name: MeanAveragePrecision
    params:
      nproc: 4
      num_classes: *num_classes
      iou_thr: 0.5
      target_fields:
        target: target
        prediction: prediction