task:
  name: DetectionTask
  params:
    backbone_name: csp_darknet_p5 #darknet53 #csp_darknet_p5 
    backbone_params:
      in_chans: &num_channels 3
      pretrained: false
    input_size: [ *num_channels, &height 640, &width 640]
    neck_name: YOLOXPAFPN
    head_name: YOLOXHead


loss:
  loss_list:
    - name: DiceLoss
      params:
        mode: binary
        target_fields:
          target: target
          input: logits
    - name: LovaszLoss
      params:
        mode: binary
        target_fields:
          target: target
          input: logits
    - name: BCEWithLogitsLoss
      params:
        target_fields:
          target: target
          input: logits

optimizers:
  name: SGD
  params:
    lr: &initial_lr 0.01
    weight_decay: 0.00005
    momentum: 0.9
    nesterov: true

schedulers:
  name: CosineAnnealingWarmRestarts
  params:
    T_0: 5
    T_mult: 2

data:
  common_params:
    data_folder: "/workdir"
    target_column: mask_path
    input_dtype: float16

  train_params:
    name: ImageSegmentationDataset
    dataloader_params: &dataloader_params
      batch_size: 64
      num_workers: 12
      shuffle: true
      drop_last: false
    params:
      path_to_datalist: "train.csv"
    transform:
      - &normalize
        name: Normalize
        params:
          mean: [0.5, 0.5, 0.5]
          std: [0.5, 0.5, 0.5]
      - &totensor
        name: ToTensorV2
    augment:
      - name: OneOf
        params:
          transforms:
            - name: RandomResizedCrop
              params:
                height: *height
                width: *width
            - name: Compose
              params:
                transforms:
                  - name: RandomCropNearInterestArea
                    params:
                      max_part_shift: 1
                      min_part_shift: 0.0
                      p: 1.0
                  - name: ShiftScaleRotate
                    params:
                      p: 1.0
                      scale_limit: 0.3
                      rotate_limit: [-180, 180]
                      shift_limit: 0.0625
                      border_mode: 0
            - name: ShiftScaleRotate
              params:
                p: 1.0
                scale_limit: 0.3
                rotate_limit: [-180, 180]
                shift_limit: 0.0625
                border_mode: 0
            - name: AlignCropNearInterestArea
              params:
                classes_of_interest: [1]
                max_pad: 0.2
                min_pad: 0.0
                p: 1.0
          p: 0.6
      - &resize
        name: LongestMaxSize
        params:
          max_size: *height
          interpolation: 2
          p: 1
      - name: OneOf
        params:
          transforms:
            - name: Blur
            - name: GaussianBlur
            - name: MedianBlur
            - name: MotionBlur
          p: 0.2
      - name: RandomFog
        params:
          p: 0.2
      - name: RandomShadow
        params:
          p: 0.2
      - name: RandomSunFlare
        params:
          p: 0.2
      - name: ChannelDropout
        params:
          p: 0.2
      - name: ChannelShuffle
        params:
          p: 0.2
      - name: ColorJitter
        params:
          p: 0.2
      - name: OneOf
        params:
          transforms:
            - name: ImageCompression
              params:
                quality_lower: 90
            - name: GaussNoise
      - name: OpticalDistortion
        params:
          p: 0.3
      - name: Equalize
        params:
          p: 0.3
      - name: ToGray
        params:
          p: 0.3
      - &pad
        name: PadIfNeeded
        params:
          min_height: *height
          min_width: *width
          border_mode: 0
          p: 1.0

  valid_params:
    name: ImageSegmentationDataset
    dataloader_params: *dataloader_params
    params:
      path_to_datalist: "valid.csv"
    transform:
      - *normalize
      - *totensor
    augment:
      - *resize
      - *pad

trainer:
  gpus: [3]
  max_epochs: 150
  progress_bar_refresh_rate: 1
  check_val_every_n_epoch: 1
  precision: 16
  amp_level: 'O3'
  amp_backend: 'apex'

log_dir: '/workdir/logs/segmentator'
experiment_name: unet_effnet_b0_lowres

logger:
  logger: tensorboard
  log_graph: false

checkpoint:
  monitor: valid/loss
  save_last: true
  mode: min
  every_n_val_epochs: 10
#  every_n_train_steps: 100

profiler:
  name: 'simple'
  save_profile: false

metrics:
  - name: AccuracyMeter
    params:
      name: accuracy
      target_fields:
        target: target
        prediction: logits
