task:
  name: ClassificationTask
  params:
    backbone_name: resnet50
    backbone_params:
      pretrained: true
      in_chans: 3
    pooling_name: Pooling
    head_name: ClassificationHead
    head_params:
      num_classes: &label_size 1743
      drop_rate : 0.2
    label_size: *label_size
    input_size: [3, &height 224, &width 224]

loss:
  loss_list:
  - name: HierarchicalMultilabelClassificationLoss
    params:
      classname2levels_path: '${SM_CHANNEL_TRAINING}/classname2levels.json'
      classname2index_path: '${SM_CHANNEL_TRAINING}/classname2index.json'
      alpha: 0.33
      target_fields:
        input: prediction
        target: target

optimizers:
  name: SGD
  params:
    lr: 0.01
    weight_decay: 0.00005
    momentum: 0.9
    nesterov: true

schedulers:
  name: OneCycleLR
  params:
    max_lr: 0.08 # should be 0.1 * sqrt(batch_size) if trained with very big batch size
    total_steps: 300000
    pct_start: 0.1
    anneal_strategy: 'cos'
    div_factor: 25
    final_div_factor: 10000
  aux_params:
    interval: 'step'

data:
  common_params:
    data_folder: "${SM_CHANNEL_TRAINING}"
    target_column: "label"
    num_classes: 1743
    lazy_init: true


  train_params:
    name: MultiLabelDataset
    dataloader_params: &dataloader_params
      num_workers: 8
      batch_size: 128
      drop_last: true
    params:
      path_to_datalist: 'train.csv'
    transform:
      - &normalize
        name: Normalize
        params:
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
      - &totensor
        name: ToTensorV2
    augment:
      - name: RandomResizedCrop
        params:
          height: *height
          width: *width
          scale: [1.0, 1.0]
          ratio: [0.75, 1.3]
      - name: HorizontalFlip
      - name: VerticalFlip
      - name: Rotate
        params:
          limit: 45
          border_mode: 0
          value: 0
      - name: GaussNoise
      - name: JpegCompression
        params:
          quality_lower: 90
      - name: ChannelShuffle
      - name: RGBShift
        params:
          r_shift_limit: 20
          g_shift_limit: 20
          b_shift_limit: 20

  valid_params:
    name: MultiLabelDataset
    dataloader_params: *dataloader_params
    params:
      path_to_datalist: 'valid.csv'
    transform:
      - *normalize
      - *totensor
    augment:
      - name: Resize
        params:
          height: *height
          width: *width
          interpolation: 1

trainer:
  gpus: 1
  auto_select_gpu: true
  max_epochs: 30
#  limit_train_batches: 10
#  limit_val_batches: 10
  progress_bar_refresh_rate: 1
  check_val_every_n_epoch: 1
  distributed_backend: dp
  precision: 32

experiment_name: &experiment_name test
log_dir: '${SM_OUTPUT_DATA_DIR}/logs'

logger:
  logger: tensorboard
#  logger: mlflow
#  experiment_name: *experiment_name
#  tags:
#    mlflow.runName: "hierarchical_multilabel_classification"
#  save_dir: "s3://test/mlruns"
#  secrets_manager:
#    region: "eu-west-1"
#    mlflow_secret: "acme/mlflow"

checkpoint:
  monitor: valid/loss
  save_last: true
  mode: min
  save_top_k: 1


metrics:
  - name: MultiLabelRecallMeter
    params:
      threshold: 0.
      num_classes: *label_size
  - name: MultiLabelRecallMeter
    params:
      threshold: 0.1
      num_classes: *label_size
  - name: MultiLabelRecallMeter
    params:
      threshold: 0.2
      num_classes: *label_size
  - name: MultiLabelRecallMeter
    params:
      threshold: 0.3
      num_classes: *label_size
  - name: MultiLabelRecallMeter
    params:
      threshold: 0.4
      num_classes: *label_size
  - name: MultiLabelRecallMeter
    params:
      threshold: 0.5
      num_classes: *label_size
  - name: MultiLabelRecallMeter
    params:
      threshold: 0.6
      num_classes: *label_size
  - name: MultiLabelRecallMeter
    params:
      threshold: 0.7
      num_classes: *label_size
  - name: MultiLabelRecallMeter
    params:
      threshold: 0.8
      num_classes: *label_size
  - name: MultiLabelRecallMeter
    params:
      threshold: 0.9
      num_classes: *label_size
  - name: MultiLabelPrecisionMeter
    params:
      threshold: 0.
      num_classes: *label_size
  - name: MultiLabelPrecisionMeter
    params:
      threshold: 0.1
      num_classes: *label_size
  - name: MultiLabelPrecisionMeter
    params:
      threshold: 0.2
      num_classes: *label_size
  - name: MultiLabelPrecisionMeter
    params:
      threshold: 0.3
      num_classes: *label_size
  - name: MultiLabelPrecisionMeter
    params:
      threshold: 0.4
      num_classes: *label_size
  - name: MultiLabelPrecisionMeter
    params:
      threshold: 0.5
      num_classes: *label_size
  - name: MultiLabelPrecisionMeter
    params:
      threshold: 0.6
      num_classes: *label_size
  - name: MultiLabelPrecisionMeter
    params:
      threshold: 0.7
      num_classes: *label_size
  - name: MultiLabelPrecisionMeter
    params:
      threshold: 0.8
      num_classes: *label_size
  - name: MultiLabelPrecisionMeter
    params:
      threshold: 0.9
      num_classes: *label_size
