task:
  name: ONNXTask
  params:
    path_to_onnx: '<onnx_path>'
    device_id: 0
    providers: ['CUDAExecutionProvider']
    inputs:
      image:
        shape: [&batch_size 8, 3, &height 32, &width 32]

data:
  TEST:
    - dataloader:
        batch_size: *batch_size
        num_workers: 4
        drop_last: false
        shuffle: false
      dataset:
        name: CIFAR10
        params:
          train: false
          download: true
          data_folder: &data_folder ${oc.env:HOME}/.cache/torchok/data/cifar10
        transform:
          - &resize
            name: Resize
            params:
              height: *height
              width: *width
          - &normalize
            name: Normalize
            params:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - &totensor
            name: ToTensorV2
  
  PREDICT:
    - dataloader:
        batch_size: *batch_size
        num_workers: 1
        drop_last: False
        shuffle: False

      dataset:
        name: CIFAR10
        params:
          train: False
          download: True
          test_mode: true
          data_folder: *data_folder
        transform:
          - *resize
          - *normalize
          - *totensor

trainer:
  accelerator: "gpu"
  max_epochs: 1

log_dir: '${oc.env:HOME}/.cache/torchok/logs/inference'
experiment_name: cifar10

checkpoint:
  monitor: valid/F1Score
  save_last: true
  mode: max

metrics:
  - name: Accuracy
    mapping: 
      preds: prediction
      target: target
  - name: F1Score
    mapping: 
      preds: prediction
      target: target
