task:
  name: ONNXTask
  params:
    path_to_onnx: '<onnx_path>'
    providers: ['CUDAExecutionProvider']
    keys_mapping_onnx2dataset:
      input.1: 'image'

data:
  TEST:
    - dataloader:
        batch_size: 8
        num_workers: 4
        drop_last: false
        shuffle: false
      dataset:
        name: CIFAR10
        params:
          train: false
          download: true
          data_folder: &data_folder ${oc.env:HOME}/.cache/torchok/data/cifar10
        transform:
          - &resize
            name: Resize
            params:
              height: 32
              width: 32
          - &normalize
            name: Normalize
            params:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - &totensor
            name: ToTensorV2
  
  PREDICT:
    - dataloader:
        batch_size: 8
        num_workers: 1
        drop_last: False
        shuffle: False

      dataset:
        name: CIFAR10
        params:
          train: False
          download: True
          test_mode: true
          data_folder: *data_folder
        transform:
          - *resize
          - *normalize
          - *totensor

trainer:
  accelerator: "gpu"
  max_epochs: 1

logger:
  log_dir: '${oc.env:HOME}/.cache/torchok/logs/'
  experiment_name: cifar10
  timestamp: '${now:%Y-%m-%d}/${now:%H-%M-%S}'
  name: TensorBoardLogger

hydra:
  run:
    dir: '${logger.log_dir}/${logger.experiment_name}/${logger.timestamp}'

callbacks:
  - name: FinalizeLogger
  - name: TQDMProgressBar
    params:
      refresh_rate: 5

metrics:
  - name: Accuracy
    mapping: 
      preds: <onnx_output>
      target: target
  - name: F1Score
    mapping: 
      preds: <onnx_output>
      target: target
