task:
  name: ClassificationTask
  compute_loss_on_valid: False
  params:
    backbone_name: swinv2_tiny_window16_256
    backbone_params:
      pretrained: true
      in_channels: 3
    pooling_name: PoolingLinear
    pooling_params:
      out_channels: 512
    head_name: ArcFaceHead
    head_params:
      num_classes: &num_classes 11318
    inputs:
      - shape: [3, &height 256, &width 256]
        dtype: 'float32'
    freeze:
      0: ['backbone.layer4']
      5: ['backbone.layer3']
      10: ['backbone.layer2']
      15: ['backbone.layer1']
      20: ['backbone']

joint_loss:
  losses:
    - name: CrossEntropyLoss
      mapping:
          input: prediction
          target: target
        
optimization:
  - optimizer:
      name: SGD
      params:
        lr: &initial_lr 0.001
        momentum: 0.9
        nesterov: true
        weight_decay: 0.00005

data:
  TRAIN:
    - dataloader:
        batch_size: 64
        num_workers: 8
        drop_last: true
        shuffle: true
      dataset:
        name: SOP
        params:
          train: true
          download: true
          data_folder: &data_folder ${oc.env:HOME}/.cache/torchok/data/sop
        transform:
          - &resize
            name: Resize
            params:
              height: *height
              width: *width
          - &normalize
            name: Normalize
            params:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - &totensor
            name: ToTensorV2
        augmentation:
          - name: HorizontalFlip
          - name: VerticalFlip
          - name: CenterCrop
            params:
              height: *height
              width: *width
              p: 1.0
          - name: OneOf
            params:
              p: 1.0
              transforms:
                - name: ElasticTransform
                  params:
                    border_mode: 1
                - name: GridDistortion
                - name: GaussNoise
                - name: ColorJitter
                  params:
                    brightness: 0.4
                    contrast: 0.4
                    saturation: 0.4
                    hue: 0.1
          - name: OneOf
            params:
              p: 1.0
              transforms:
                - name: ElasticTransform
                  params:
                    border_mode: 1
                - name: GridDistortion
                - name: GaussNoise
                - name: ColorJitter
                  params:
                    brightness: 0.4
                    contrast: 0.4
                    saturation: 0.4
                    hue: 0.1
  VALID:
    - dataloader:
        batch_size: 8
        num_workers: 4
        drop_last: false
        shuffle: false
      dataset:
        name: SOP
        params:
          train: false
          download: true
          data_folder: *data_folder
        transform:
          - *resize
          - *normalize
          - *totensor

trainer:
  gpus: [0]
  max_epochs: 40
  num_sanity_val_steps: 0

logger:
  log_dir: '${oc.env:HOME}/.cache/torchok/logs/'
  experiment_name: sop
  name: TensorBoardLogger

checkpoint:
  monitor: valid/HitAtKMeter
  save_last: true
  mode: max
  save_top_k: 2

metrics:
  - name: Accuracy
    mapping: 
      preds: prediction
      target: target
    phases: [TRAIN]

  - name: HitAtKMeter
    params:
      k: 1
      dataset_type: classification
      normalize_vectors: True
      search_batch_size: 256
    mapping:
      vectors: embeddings
      targets: target
    phases: [VALID]
