task:
  name: RepresentationLearnTask
  params:
    backbone_name: resnet18
    backbone_params:
      pretrained: true
      in_channels: 3
    pooling_name: Pooling
    head_name: LinearHead
    head_params:
      out_channels: &emb_size 512
      normalize: true
    inputs:
      - shape: [3, &height 224, &width 224]
        dtype: 'float32'
    num_classes: 11318

joint_loss:
  losses:
    - name: ContrastiveLoss
      params:
        margin: 1.0
      mapping:
        emb1 : emb1
        emb2 : emb2
        R : R


optimization:
  - optimizer: 
      name: Adam
      params:
        lr: &initial_lr 0.0001
    scheduler:
      name: OneCycleLR
      params:
        epochs: 20
        steps_per_epoch: 100
        max_lr: *initial_lr
        pct_start: 0.1

data:
  TRAIN:
    - dataloader:
        batch_size: 64
        num_workers: 4
        drop_last: true
        shuffle: true
      dataset:
        name: SOP
        params:
          image_dtype: float32
          train: true
          download: true
          data_folder: &data_folder ${oc.env:HOME}/.cache/torchok/data/sop
        transform:
          - &resize
            name: Resize
            params:
              height: *height
              width: *width
          - &normalize
            name: Normalize
            params:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - &totensor
            name: ToTensorV2
        augment:
          - name: HorizontalFlip
          - name: VerticalFlip
          - name: Compose
            params:
              p: 0.5
              transforms:
                - name: PadIfNeeded
                  params:
                    min_height: *height
                    min_width: *width
                - name: CenterCrop
                  params:
                    height: *height
                    width: *width
          - name: OneOf
            params:
              p: 1.0
              transforms:
                - name: ElasticTransform
                  params:
                    border_mode: 1
                - name: GridDistortion
                - name: GaussNoise
                - name: ColorJitter
                  params:
                    brightness: 0.4
                    contrast: 0.4
                    saturation: 0.4
                    hue: 0.1

trainer:
  accelerator: 'gpu'
  max_epochs: 20
  log_every_n_steps: 10

hydra:
  run:
    dir: '${logger.log_dir}/${logger.experiment_name}/${logger.timestamp}'

logger:
  log_dir: '${oc.env:HOME}/.cache/torchok/logs/'
  experiment_name: toilets
  timestamp: '${now:%Y-%m-%d}/${now:%H-%M-%S}'
  name: TensorBoardLogger

checkpoint:
  monitor: valid/loss
  save_last: true
  mode: min
  export_to_onnx: true

metrics: []
