task:
  name: SegmentationTask
  params:
    backbone_name: hrnet_w18
    backbone_params:
      pretrained: true
      in_channels: 3
    neck_name: HRNetSegmentationNeck
    neck_params:
      start_block: 2
    head_name: HRNetSegmentationHead
    head_params:
      num_classes: &num_classes 3
    inputs:
      - shape: [1, 3, &height 256, &width 256]
        dtype: 'float32'

joint_loss:
  losses:
    - name: CrossEntropyLoss
      mapping:
          input: prediction
          target: target
    - name: DiceLoss
      params:
        mode: multiclass
      mapping:
        input: prediction
        target: target

optimization:
  - optimizer: 
      name: Adam
      params:
        lr: 0.0001
    scheduler:
      name: ExponentialLR
      params:
        gamma: 0.97

data:
  TRAIN:
    - dataloader:
        batch_size: 8
        num_workers: 4
        drop_last: true
        shuffle: true
      dataset:
        name: SweetPepper
        params:
          train: true
          download: true
          data_folder: &data_folder ${oc.env:HOME}/.cache/torchok/data/sweet_pepper
        transform:
          - &resize
            name: Resize
            params:
              height: *height
              width: *width
              interpolation: 0
          - &normalize
            name: Normalize
            params:
              mean: [ 0.485, 0.456, 0.406 ]
              std: [ 0.229, 0.224, 0.225 ]
          - &totensor
            name: ToTensorV2
        augment:
          - name: HorizontalFlip
          - name: VerticalFlip
          - name: Compose
            params:
              p: 0.5
              transforms:
                - name: PadIfNeeded
                  params:
                    min_height: *height
                    min_width: *width
                - name: CenterCrop
                  params:
                    height: *height
                    width: *width
          - name: OneOf
            params:
              p: 1.0
              transforms:
                - name: ElasticTransform
                  params:
                    border_mode: 1
                - name: GridDistortion
                - name: GaussNoise
                - name: ColorJitter
                  params:
                    brightness: 0.4
                    contrast: 0.4
                    saturation: 0.4
                    hue: 0.1
          - name: OneOf
            params:
              p: 1.0
              transforms:
                - name: ElasticTransform
                  params:
                    border_mode: 1
                - name: GridDistortion
                - name: GaussNoise
                - name: ColorJitter
                  params:
                    brightness: 0.4
                    contrast: 0.4
                    saturation: 0.4
                    hue: 0.1

  VALID:
    - dataloader:
        batch_size: 8
        num_workers: 4
        drop_last: false
        shuffle: false
      dataset:
        name: SweetPepper
        params:
          train: false
          download: true
          data_folder: *data_folder
        transform:
          - *resize
          - *normalize
          - *totensor

trainer:
  accelerator: 'gpu'
  max_epochs: 30
  log_every_n_steps: 1000

logger:
  log_dir: '${oc.env:HOME}/.cache/torchok/logs/'
  experiment_name: sweet_pepper
  name: TensorBoardLogger

checkpoint:
  monitor: valid/JaccardIndex
  save_last: true
  mode: max

metrics:
  - name: JaccardIndex
    params:
      num_classes: 3
      ignore_index: 0
    mapping: 
      preds: prediction
      target: target

