task:
  name: DetectionTask
  params:
    backbone_name: csp_darknet_p5 #darknet53 #csp_darknet_p5 
    backbone_params:
      in_chans: &num_channels 3
      pretrained: false
    input_size: [ *num_channels, &height 640, &width 640]
    neck_name: YOLOXPAFPN
    head_name: YOLOXHead
    head_params:
      num_classes: &num_classes 1
    hat_name: YOLOXHat
    hat_params:
      mode: binary
      conf_thr: 0.25

loss:
  loss_list:
    - name: BCEWithLogitsLoss
      params:
        target_fields:
          target: cls_targets
          input: cls_pred
    - name: DetectionIoULoss
      params:
        mode: square
        target_fields:
          target: bbox_target
          input: bbox_pred
    - name: BCEWithLogitsLoss
      params:
        target_fields:
          target: obj_target
          input: obj_pred
  weight: [1, 10, 1] 


# optimizers:
#   name: SGD
#   params:
#     lr: &initial_lr 0.01
#     weight_decay: 0.0005
#     momentum: 0.9
#     nesterov: true

optimizers:
  name: Adam
  params:
    lr: &initial_lr 0.001
    weight_decay: 0.0005

schedulers:
  name: ExponentialLR
  params:
    gamma: 0.98


data:
  common_params:
    data_folder: "/workdir/kaggle_data/"
    input_dtype: float16

  train_params:
    name: DetectionDataset
    dataloader_params: &dataloader_params
      use_custom_collate_fn: true
      batch_size: 64
      num_workers: 12
      shuffle: true
      drop_last: false
    params:
      # path_to_datalist: "small_train.csv"
      # path_to_datalist: "train.csv"
      path_to_datalist: "train_without_neg.csv"
    transform:
      - &normalize
        name: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          # std: [0.5, 0.5, 0.5]
      - &resize
        name: Resize
        params:
            height: *height
            width: *width
      - &totensor
        name: ToTensorV2
    augment:
      - name: HorizontalFlip
      # - name: VerticalFlip
      # - name: OneOf
      #   params:
      #     transforms:
      #       - name: Blur
      #       - name: GaussianBlur
      #       - name: MedianBlur
      #       - name: MotionBlur
      #     p: 0.2
      # - name: RandomFog
      #   params:
      #     p: 0.2
      # - name: RandomShadow
      #   params:
      #     p: 0.2
      # - name: RandomSunFlare
      #   params:
      #     p: 0.2
      # - name: ChannelDropout
      #   params:
      #     p: 0.2
      # - name: ChannelShuffle
      #   params:
      #     p: 0.2
      # - name: ColorJitter
      #   params:
      #     p: 0.2
      # - name: OneOf
      #   params:
      #     transforms:
      #       - name: ImageCompression
      #         params:
      #           quality_lower: 90
      #       - name: GaussNoise
      # - name: Equalize
      #   params:
      #     p: 0.3
      # - name: ToGray
      #   params:
      #     p: 0.3
      
  valid_params:
    name: DetectionDataset
    dataloader_params: *dataloader_params
    params:
      path_to_datalist: "valid_without_neg.csv"
    transform:
      - *normalize
      - *totensor
    augment:
      - *resize
    #   - *pad

trainer:
  gpus: [0]
  max_epochs: 100
  progress_bar_refresh_rate: 1
  check_val_every_n_epoch: 1
  precision: 16
  amp_level: 'O2'
  amp_backend: 'apex'

log_dir: 'logs/detectors/'
experiment_name: yolox

logger:
  logger: tensorboard
  log_graph: false

checkpoint:
  monitor: valid/mAP50
  save_last: true
  mode: max
  every_n_val_epochs: 1
#  every_n_train_steps: 100

profiler:
  name: 'simple'
  save_profile: false

metrics:
  - name: MeanAveragePrecision
    phases: ['train', 'valid', 'test']
    params:
      nproc: 1
      num_classes: 2
      iou_thr: 0.5
      target_fields:
        target: target
        prediction: prediction
