name: Test checks

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Install python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: torchok
          environment-file: environment.yml
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate torchok
          find `pwd`/tests/ -name 'test_*.py' \
          -not -path "`pwd`/tests/models/*" \
          -not -path "`pwd`/tests/constructor/*" \
          -not -path "`pwd`/tests/metrics/*" \
           | xargs python -m unittest 
          python -m unittest discover -s tests/data/ -p "test_*.py"
